name: dart_portfolio
description: A new Jaspr project
version: 0.0.1

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  jaspr: ^0.19.0
  jaspr_router: ^0.7.0
  jaspr_tailwind:
    git:
      url: git@github.com:denniskaselow/jaspr_tailwind.git

dev_dependencies:
  build_runner: ^2.4.0
  jaspr_web_compilers: ^4.1.5
  jaspr_builder: ^0.19.0
  jaspr_lints: ^0.3.1
  lints: ^5.0.0

jaspr:
  mode: server

